### ISSUE TITLE
Multiple := in an expression leaves .. unclear.

### ISSUE THREAD

**Issue by barryrowlingson** [moodymudskipper/dotdot#1]
What is the expected result of:
```
> x=4 ; y=7; x := (y := .. + 2)
```

does the `..` refer to `y` or `x`? 
```
> x
[1] 6
> y
[1] 6
```

 `x`. 

But it means the part of the expression `y := .. + 2` is now horribly dependent on an outside context, namely the value of `x`, or possibly even something further away.

Better to avoid `..` and be explicit with whichever of these is wanted:
```
> x=4 ; y=7; x := (y := y + 2)
> x=4 ; y=7; x := (y := x + 2)
```

I would think this is also a bit unobvious:

```
> x=4 ; x := (function(z){z=3;z :=..;z})(..)
> x
[1] 4
```
since even the `..` inside the function evaluates to the LHS of the outside `:=`. Compare:
```
> x=4 ; x := (function(z){z=3;z})(..)
> x
[1] 3
```

**Comment by moodymudskipper** [comment]
Hi Barry, good to see you here.

These are interesting edge cases. The 1st one:

`
x=4 ; y=7; x := (y := .. + 2)
`

* The result might be counter-intuitive when you think of the `..` as a variable, but not when you think about it as a shorthand for the leftmost variable, the first `:=` replaces the dots with the name of the variable we assign too. 

I admit I need better doc though.

In the defense of the operator :

* `x=4 ; y=7; x <- (y := .. + 2)` and `x=4 ; y=7; x := (y <- .. + 2)` work as you probably intended, and it makes sense to use `:=` only when you need it, not to replace every assignment (I'll make sure to make this explicit in the doc).
* Something like `z <- (x := .. + 1) + (y:= .. +1)` works and isn't ambiguous, and it's the closest thing to your example that i can think of when trying to imagine a realistic thing that somebody would want to do with several `:=`. 
* The "competitor" `magrittr` doesn't do better and I have never read anyone getting confused about  : `x %<>% (y %<>% {. + 2})` triggering an error.

> But it means the part of the expression y := .. + 2 is now horribly dependent on an outside context, namely the value of x, or possibly even something further away.

OR it's just replaced by the name of the lhs of the first  evaluated `:=` :), I think when seen this way it's not so counter-intuitive. I just need the right pitch.

Your second example `x=4 ; x := (function(z){ z=3; z := .. ; z})(..)` is easier to comprehend when you see it this way.

I agree that this can be problematic though, especially when writing on several lines, when we lose sense of the context, I'm thinking about a `:=` that would be "forgotten" in the code. like in :

```
fun := function(z){ 
  # insert a dozen more lines of code
  z <- 3
  z := .. + 2
}

fun(3)
# Error in fun + 2 : non-numeric argument to binary operator
```

In that case it's really straightforward to debug though. 

I believe these are not "bugs" but edge cases that may confuse a user that would try weird stuff without reading the doc (except the part about the doc for now).

I propose the following in the details section of the doc + readme : 
 
> `:=` is NOT meant to be a complete replacement of the `<-` operator, the latter is explicit in the absence of `..` , so more readable, is faster (though we're speaking nano seconds), and won't clutter your `traceback()` when debugging. 
> 
> `:=` can be used several times in a statement like `z <- (x := .. + 1) + (y:= .. +1)` but it never makes sense to use it `:=` several times in an assignment such as `x := (y := .. + 2)` as all the `..` will be replaced by the name of the variable on the lhs of the first evaluated `:=` in any case.  It can even produce counter intuitive output, see examples.

additional examples :

```
x <- 4
y <- 7
z <- (x := .. + 1) + (y:= .. +1)
x
y
z

#  using several  `:=` in an assignment is unuseful and potentially confusing
x <- 4
y <- 7
x := (y := .. + 2) # same as `x <- (y := x + 2)` 
x
y

# Use it unambiguously
x <- 4
y <- 7
x <- (y := .. + 2)
x
y

x <- 4
y <- 7
x := (y <- .. + 2)
x
y
```

What do you think ?

**Comment by moodymudskipper** [comment]
I made changes to the readme and the help file. Leaving this open for a couple days in case you want to add something.
