### ISSUE TITLE
dotdot usage inside `[`?

### ISSUE THREAD

**Issue by daranzolin** [moodymudskipper/dotdot#9]
This is unrelated to assignment and probably out-of-scope for this package, but is it possible to subset with `..`? E.g.:

```
mtcars$mpg[..>20]
```
Instead of:
```
mtcars$mpg[mtcars$mpg>20]
```

**Comment by moodymudskipper** [comment]
I don't think this can be done without overriding `[`, but you might like {inops} : https://github.com/moodymudskipper/inops

``` r
library(inops, warn.conflicts = FALSE)
mtcars$mpg %[>% 20
#>  [1] 21.0 21.0 22.8 21.4 24.4 22.8 32.4 30.4 33.9 21.5 27.3 26.0 30.4 21.4
```
